spring:
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    platform: org.hibernate.dialect.MySQL5Dialect
    url: jdbc:mysql://localhost:3306/dbcitrino
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver

management:
  security:
    enabled: false

logging:
  level:
    ROOT: INFO